export const PLAYER_CONFIG = {
    MOVE_SPEED: 10,
    SPRINT_MULTIPLIER: 2,
    GRAVITY: -20,
    
    CAMERA_HEIGHT: 1.8,
    PLAYER_HEIGHT: 2.0,
    PLAYER_RADIUS: 0.5,
    
    HITBOX_WIDTH: 1.0,
    HITBOX_DEPTH: 1.0,
    RAYCAST_DISTANCE: 1.2,
    COLLISION_MARGIN: 0.0001,
    WALL_COLLISION_FACTOR: 1.01,
    COLLISION_SMOOTHING: 0.5,
    COLLISION_ANGLE_THRESHOLD: 15,
    SPHERE_CAST_OFFSET: 0.1,

    STAIR_DETECTION_MARGIN_X: 1.5,
    STAIR_DETECTION_MARGIN_Z: 1.0,
    STAIR_HEIGHT_TOLERANCE: 1.5,
    STAIR_MOVEMENT_SPEED: 0.2,
    
    INITIAL_PLAYER_HEIGHT: 150.0,
    
    PLAYER_IMMORTAL: true
};
